### PR TITLE
Bugfix/dns

### LINKED ISSUE #1727: [bug]: DNS Issue in Services
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### EmbassyOS Version

0.3.1.1

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.18

### Browser

Firefox

### Browser Version

102

### Current Behavior

` WARN embassy::net::dns: Non A-Record requested for vaultwarden.embassy. `

Device is bep/chiming every 10-15min, becoming unavailable shortly before bep/chime.  The above error message is prevalent

### Expected Behavior

Device runs without constantly restarting

### Steps to Reproduce

1. Latest image
2. Recover / Use Drive
3. See issue

### Anything else?

This is a symptom of a larger, yet unknown issue.  @gStart9 has run into several production errors that indicate DNS problems, i.e. involving SMB share

### PR DESCRIPTION
**Pull request by dr-bonez**
should close #1727

### CODE REVIEW

File: backend/src/net/wifi.rs [hunk 1]
```diff
@@ -801,7 +801,6 @@ pub async fn synchronize_wpa_supplicant_conf<P: AsRef<Path>>(
         .arg("up")
         .invoke(ErrorKind::Wifi)
         .await?;
-    Command::new("dhclient").invoke(ErrorKind::Wifi).await?;
```
Comment (Blu-J) [inline backend/src/net/wifi.rs:804]: If I remember, this is redundant because the initialization.sh

**Review by Blu-J — APPROVED** [review]

File: backend/src/net/wifi.rs (hunk 1 above)
Comment (dr-bonez) [reply backend/src/net/wifi.rs:804]: We aren't using dhclient anymore. Relying on systemd-resolved
