### PR TITLE
Bugfix/fix unstable cleanup

### LINKED ISSUE #905: [bug]: Service Installation failure results in package stuck mid-install
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.15.7

### Browser

Firefox

### Browser Version

94.0.2

### Current Behavior

Installing a bunch of services (~10) at once causes the service to be stuck at the downloading step (52%) and throws the following error:

```
Failed: Filesystem I/O Error: request or response body error: error reading a body from connection: end of file before message length reached 
```

Running `systemctl restart embassy` clears the installing services from the UI, but this error appears in logs:

```
Dec 05 05:54:05 embassy-7fed63b1 embassyd[6257]: Dec 05 05:54:05.549  WARN shutdown: embassy::context::rpc: 1 RPC Context(s) are still being held somewhere. This is likely a mistake.
Dec 05 05:54:05 embassy-7fed63b1 embassyd[6257]: The application panicked (crashed).
Dec 05 05:54:05 embassy-7fed63b1 embassyd[6257]: Message:  RpcContext used after shutdown!
Dec 05 05:54:05 embassy-7fed63b1 embassyd[6257]: Location: src/context/rpc.rs:339
Dec 05 05:54:05 embassy-7fed63b1 embassyd[6257]: Backtrace omitted.
```

Running `embassy-cli db dump` reveals the service stuck at installing does not exist. 

There are no IO errors in dmesg logs.

### Expected Behavior

All services should install without error when installing many in parallel.

### Steps to Reproduce

1. Start installing all services from the marketplace.
2. Notice that one of them will fail as you install many at once. 
3. The failed install will be stuck at 53% until embassyd is restarted.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dr-bonez**
fixes #905

### CODE REVIEW

File: appmgr/src/install/mod.rs [hunk 1]
```diff
@@ -305,11 +312,11 @@ pub async fn sideload(
     };
     // gc the map
     let mut guard = ctx.rpc_stream_continuations.lock().await;
-    let gced = std::mem::take(&mut *guard)
+    let garbage_collected = std::mem::take(&mut *guard)
```
Comment (Blu-J) [inline appmgr/src/install/mod.rs:315]: Thanks for the full name

**Review by Blu-J — APPROVED** [review]
