### PR TITLE
correctly handle self as current dependent

### LINKED ISSUE #926: [bug]: bitcoind complains that it will stop if I stop it
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

030

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

backend error

### Browser

Other

### Browser Version

backend error

### Current Behavior

When I go to stop bitcoind, the affected services modal pops up telling me that bitcoind will be affected if I stop bitcoind. This is obvious and unnecessary.

### Expected Behavior

The service should simply stop, no modal necessary

### Steps to Reproduce

1. Start bitcoind
2. Stop bitcoind
3. View modal

### Anything else?

Screen Shot 2021-12-08 at 6 43 48 PM
Screen Shot 2021-12-08 at 6 42 48 PM

### PR DESCRIPTION
**Pull request by dr-bonez**
fixes #926

### CODE REVIEW

File: appmgr/src/install/mod.rs [hunk 1]
```diff
@@ -997,6 +996,8 @@ pub async fn install_s9pk<R: AsyncRead + AsyncSeek + Unpin>(
             *main_status = prev.status.main;
             main_status.save(&mut tx).await?;
         }
+        remove_current_dependents(&mut tx, pkg_id, prev.current_dependencies.keys()).await?; // remove previous
+        add_current_dependents(&mut tx, pkg_id, &current_dependencies).await?; // add new
```
Comment (ProofOfKeags) [inline appmgr/src/install/mod.rs:1000]: maybe `remove_from_previous_dependencies_dependents`, `add_to_dependencies_current_dependents`

Comment (ProofOfKeags) [reply appmgr/src/install/mod.rs:1000]: or `remove from previous set of dependencies`, `add to new set of dependencies`

**Review by elvece — APPROVED** [review]
