### PR TITLE
retry failed pause

### LINKED ISSUE #941: [bug]: Docker freeze crash preventing backups
Two users have hit this while running normal backups:

`docker error 500 - Docker responded with status code 500: {"message":"Cannot pause container 30936156bd4cc756f7acb541d6aa88da3aa828bacc41c2c0af08b133c32f95ef: OCI runtime pause failed: unable to freeze: unknown"}`

@k0gen's crashed on synapse, while @dme1sec had the same bug but with vaultwarden.

### PR DESCRIPTION
**Pull request by dr-bonez**
fixes #941

### CODE REVIEW

**Review by Blu-J — APPROVED** [review]

File: appmgr/src/manager/mod.rs [hunk 1]
```diff
@@ -561,11 +561,24 @@ async fn start(shared: &ManagerSharedState) -> Result<(), Error> {
 
 #[instrument(skip(shared))]
 async fn pause(shared: &ManagerSharedState) -> Result<(), Error> {
-    shared
-        .ctx
-        .docker
-        .pause_container(&shared.container_name)
-        .await?;
+    let mut res = Ok(());
```
Comment (Blu-J) [inline appmgr/src/manager/mod.rs:564]: Would be nice to have this as an abstraction, but a one off isn't bad.

**Review by Blu-J — APPROVED** [review]
