### PR TITLE
better eager loading and better error messaging for backup flow

### LINKED ISSUE #1364: [bug]: Password validation fails first time when creating/restoring backup.
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

Catalina

### Browser

Firefox

### Browser Version

96.0.3

### Current Behavior

Entering your master password fails on first attempt when (1) creating a new backup on top of an existing one or (2) restoring from backup. It always works on the 2nd attempt.

### Expected Behavior

Should work on first try if correct

### Steps to Reproduce

1. create a backup.
2. attempt to restore.
3. notice password appears to be invalid.
4. try again.
5. notice it works.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MattDHill**
closes #1364 

Also does better eager loading in general

### CODE REVIEW

**Review by dr-bonez — APPROVED** [review]

File: frontend/projects/ui/src/app/pages/server-routes/restore/restore.component.ts [hunk 1]
```diff
@@ -25,21 +28,24 @@ export class RestorePage {
...
 
   async presentModalPassword(
     target: MappedBackupTarget<CifsBackupTarget | DiskBackupTarget>,
   ): Promise<void> {
     const options: GenericInputOptions = {
-      title: 'Master Password Required',
+      title: 'Password Required',
       message:
-        'Enter your master password. On the next screen, you will select the individual services you want to restore.',
+        'Enter the master password that was used to encrypt this backup. On the next screen, you will select the individual services you want to restore.',
```
Comment (elvece) [inline frontend/projects/ui/src/app/pages/server-routes/restore/restore.component.ts:40]: to be clear, it does not have to be the same as the embassy login pw?

**Review by elvece — APPROVED** [review]
